language: go

go:
  - tip

install:
  - go get gopkg.in/redis.v3
  - go get github.com/mattn/goveralls
  - go get github.com/modocache/gover

script:
  - go test -v -coverprofile=pong.coverprofile
  - go test -v -coverprofile=session.coverprofile ./session/memory_session
  - $HOME/gopath/bin/gover
  - ls
  - $HOME/gopath/bin/goveralls -coverprofile=gover.coverprofile -service=travis-ci